import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/styles/globals.css";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { AuthSessionProvider } from "@/lib/session-provider";
import { ApolloClientProvider } from "@/lib/apollo-provider";
import { SidebarProvider } from "@/lib/sidebar-context";
import { StoreInitializer } from "@/components/store-initializer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground`}
      >
        <AuthSessionProvider>
          <ApolloClientProvider>
            <SidebarProvider>
              <ThemeProvider>
                <StoreInitializer />
                {children}
              </ThemeProvider>
            </SidebarProvider>
          </ApolloClientProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
